
--A-1
SELECT tb.CUSTOMID, SUM(PRICE*QUANTITY)
FROM TBL_BUY tb , TBL_PRODUCT tp 
WHERE tp.PCODE =tb.PCODE 
AND CUSTOMID = 'mina012'
GROUP BY tb.CUSTOMID ;

--A-2
SELECT *
FROM TBL_BUY tb 
JOIN TBL_CUSTOM tc
ON	tb.CUSTOMID  = tc.CUSTOM_ID 
WHERE tc.NAME LIKE '%길동';

--A-3
SELECT *
FROM TBL_CUSTOM tc
JOIN TBL_BUY tb
ON tc.CUSTOM_ID = tb.CUSTOMID
JOIN TBL_PRODUCT tp 
ON tb.PCODE = tp.PCODE 
WHERE tc.AGE >25;

--A-4
SELECT CUSTOMID ,SUM(QUANTITY*PRICE) 
FROM TBL_BUY tb 
JOIN TBL_PRODUCT tp 
ON tp.PCODE  = tb.PCODE
WHERE PNAME LIKE '%사과%'
GROUP BY CUSTOMID ;

--A-5 //having 사용하기
SELECT CUSTOMID ,SUM(QUANTITY*PRICE) 
FROM TBL_BUY tb , TBL_PRODUCT tp 
WHERE tb.PCODE =tp.PCODE 
GROUP BY CUSTOMID
HAVING SUM(QUANTITY*PRICE) BETWEEN 100000 AND 200000;

--B-1
SELECT  CUSTOMID, AGE, PCODE
FROM TBL_CUSTOM tc ,TBL_BUY tb 
WHERE tc.CUSTOM_ID = tb.CUSTOMID
AND AGE BETWEEN 20 AND 29;

--B-2 ★★★★★
SELECT min(AGE), COUNT(QUANTITY) 
FROM TBL_BUY tb
JOIN TBL_CUSTOM tc
ON tb.CUSTOMID =tc.CUSTOM_ID 
WHERE AGE = (SELECT min(AGE) FROM TBL_CUSTOM tc);

--B-3 2023년 하반기 구매금액을 고객ID별로 조회하시오. 금액이 높은 순서부터 조회하세요
SELECT CUSTOMID ,SUM(QUANTITY*PRICE)
FROM TBL_BUY tb 
JOIN TBL_CUSTOM tc  ON tc.CUSTOM_ID =tb.CUSTOMID
JOIN TBL_PRODUCT tp ON	tb.PCODE = tp.PCODE 
WHERE BUY_DATE BETWEEN '2023-07-01' AND '2023-12-31'
GROUP BY CUSTOMID 
ORDER BY SUM(QUANTITY*PRICE) desc;

--B-4 ★★★★★
SELECT CUSTOM_ID ,NAME, AGE, EMAIL
FROM TBL_CUSTOM tc 
WHERE tc.CUSTOM_ID IN (
	SELECT tb.CUSTOMID
	FROM TBL_BUY tb
	WHERE TO_CHAR(BUY_DATE,'yyyy')='2024'
	GROUP BY tb.CUSTOMID
	HAVING COUNT(*)>=1);
	
--B-5 tb. tp. 잘 사용하기
SELECT tb.CUSTOMID, tb.PCODE, SUM(tb.QUANTITY * tp.PRICE) AS "구매금액"
FROM TBL_BUY tb
JOIN TBL_PRODUCT tp ON tp.PCODE = tb.PCODE
GROUP BY tb.CUSTOMID, tb.PCODE
ORDER BY tb.CUSTOMID ASC, tb.PCODE ASC;

--C-1
SELECT tp.PCODE, tp.PNAME "상품명", avg(tb.QUANTITY) "평균 구매 개수"
FROM TBL_BUY tb
JOIN TBL_PRODUCT tp ON tb.PCODE =tp.PCODE 
WHERE tp.PRICE >10000
GROUP BY tp.PCODE, tp.PNAME
ORDER BY tp.PCODE ;

--C-2
SELECT CUSTOM_ID,NAME, count(tl.QUANTITY), tl.BUY_DATE
FROM 
(SELECT QUANTITY, BUY_DATE, CUSTOMID
FROM TBL_PRODUCT tp 
JOIN TBL_BUY tb  ON tp.PCODE =tb.PCODE 
WHERE tp.PNAME LIKE '%진라면%')tl
JOIN TBL_CUSTOM tc ON tc.CUSTOM_ID =tl.CUSTOMID
GROUP BY CUSTOM_ID,NAME,tl.BUY_DATE;

--C-3 유사문제 슼

--C-4 tp.pcode를 쓸 때 하나만 사용하기.. 코드가 꼬인다 ㅠㅠ
SELECT tp.PCODE, tp.PNAME ,COUNT(tb.QUANTITY) , SUM(tb.QUANTITY*tp.PRICE) 
FROM TBL_BUY tb , TBL_PRODUCT tp 
WHERE tb.PCODE = tp.PCODE 
GROUP BY tp.PCODE, tp.PNAME
ORDER BY tp.PCODE ASC;


--C-5
WITH MINAGD
AS(
	SELECT *
	FROM TBL_BUY tb 
	WHERE CUSTOMID = 'twice' OR CUSTOMID = 'hongGD'
)
SELECT tp.PNAME, minaGD.quantity,tp.PRICE
FROM MINAGD
JOIN TBL_PRODUCT tp 
ON MINAGD.PCODE = tp.PCODE
ORDER BY PRICE DESC;



SELECT tp.PNAME , tb.QUANTITY , tp.PRICE  
FROM TBL_PRODUCT tp
JOIN TBL_BUY tb ON tp.PCODE = tb.PCODE 
WHERE CUSTOMID = 'twice' OR CUSTOMID = 'hongGD'
ORDER BY PRICE DESC;


--D-1
SELECT tb.CUSTOMID, SUM(QUANTITY*PRICE) 
FROM TBL_BUY tb 
JOIN TBL_PRODUCT tp ON tp.PCODE =tb.PCODE 
WHERE tb.PCODE = (SELECT tp.PCODE FROM TBL_PRODUCT tp WHERE tp.PNAME LIKE '%진라면%')
GROUP BY tb.CUSTOMID
ORDER BY tb.CUSTOMID DESC;

--D-2
SELECT tp.PCODE ,tp.PNAME ,COUNT(tb.QUANTITY) "팔린 개수" , SUM(tb.QUANTITY*tp.PRICE) "총 팔린 금액"
FROM TBL_BUY tb 
JOIN TBL_PRODUCT tp ON tp.PCODE =tb.PCODE
GROUP BY tp.PCODE ,tp.PNAME
ORDER BY COUNT(tb.QUANTITY) DESC;

--D-3
SELECT tp.PCODE , AVG(tl.AGE)
FROM  
(SELECT tc.AGE, tb.PCODE
FROM TBL_CUSTOM tc 
JOIN TBL_BUY tb ON tb.CUSTOMID = tc.CUSTOM_ID ) tl
JOIN TBL_PRODUCT tp ON tl.PCODE = tp.PCODE 
WHERE tp.PNAME LIKE '%진라면%'
GROUP BY tp.PCODE ;

--D-4
SELECT tb.CUSTOMID , SUM(tb.QUANTITY*tp.PRICE) 
FROM TBL_BUY tb
JOIN TBL_CUSTOM tc ON tb.CUSTOMID =tc.CUSTOM_ID 
JOIN TBL_PRODUCT tp ON tb.PCODE = tp.PCODE 
WHERE tc.AGE <30
GROUP BY tb.CUSTOMID 
ORDER BY SUM(tb.QUANTITY*tp.PRICE) DESC;
