--JDBC 프로젝트를 위한 SQL 테스트

--회원 정보 수정 : email, age
UPDATE TBL_CUSTOM SET EMAIL = 'test@gmail.com',age =22
WHERE CUSTOM_ID = 'nayeong';


--탈퇴:
DELETE FROM TBL_CUSTOM 
WHERE CUSTOM_ID ='나나나';

SELECT BUY_IDX
FROM TBL_BUY TB
LEFT JOIN TBL_PRODUCT TP
ON TB.PCODE = TP.PCODE
WHERE TB.CUSTOMID = 'mina012';